apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-hhcq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-hhcq
    app.kubernetes.io/part-of: jvm-build-suite-application-mwtm
  name: jvm-build-suite-component-hhcq
  namespace: jvm-build-axli-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jvm-build-suite-component-hhcq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: jvm-build-suite-component-hhcq
    spec:
      containers:
      - image: quay.io/rh_ee_tnevrlka/test-images@sha256:d95f3de228202d30ac07d292625f0d5c4fddcc4bc4ea36ee07d9eb9dbce41671
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
